application: taiwan-airmap
version: 3-1
runtime: php55
api_version: 1
threadsafe: yes

handlers:

#image
- url: /image/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: assets/image/\1
  upload: assets/image/(.*\.(bmp|gif|ico|jpeg|jpg|png))

#css
- url: /css/(.*\.css)
  static_files: assets/dist/\1
  upload: assets/dist/(.*\.css)
  mime_type: text/css

#js
- url: /js/(.*\.js)
  static_files: assets/dist/\1
  upload: assets/dist/(.*\.js)
  mime_type: application/javascript

#json
- url: /json/airmap\.json
  script: script/airmap.php
- url: /json/deactivesite\.json
  script: script/airmap.php
  
- url: /json/sinicaHistory\.json
  script: script/sinicaHistory.php
- url: /json/asusAirbox\.json.*
  script: script/asusAirbox.php


#scripts
- url: /script/(.*)
  script: script/\1
- url: /image/markerIcon
  script: script/markerIcon.php

#static html
- url: /recruit
  static_files: html/recruit.html
  upload: html/recruit.html
  
- url: /about
  static_files: html/about.html
  upload: html/about.html

- url: /list
  static_files: html/list.html
  upload: html/list.html

- url: /site
  static_files: html/site.html
  upload: html/site.html

- url: /.*
  static_files: html/map.html
  upload: html/map.html

# - url: /.*
#   script: script/notfound.php

skip_files:
- ^(.*/)?.*/node_modules/.*$
- ^(node_modules/.*)
- ^(.git/.*)
- ^(src/.*)